### ISSUE TITLE
Compatibility with JSON Schema draft v4?

### ISSUE THREAD

**Issue by marcosnils** [unindented/fake-json#1]
Hi,

This seems like a nice project, well tested and I could really use it in my organization. However, by performing a quick search I couldn't find any reference regarding to JSON Schema draft v4 features (https://github.com/json-schema/json-schema/wiki/ChangeLog)

Is there any plans to support the latest features in the near future?. 

Keep up the good work!.

**Comment by unindented** [comment]
@pateketrueke I now recommend your library in my `README`, and have marked mine as abandoned.
